### ISSUE TITLE
Unsupported opperand +

### ISSUE THREAD

**Issue by PhilippNuspl** [Antonio-JP/dd_functions#4]
```
f1 = DDFinite.random_element(max_order=1)
f2 = DDFinite.random_element(max_order=1)
f1+f2
```
yields the error

> TypeError: unsupported operand type(s) for +: 'DDFunction' and 'DDFunction'

The command `f1.add(f2)` yields 

> AttributeError: 'int' object has no attribute 'parent'

Computations with multiplication * works fine.

**Comment by Antonio-JP** [comment]
This issue was no longer replicated in commit 78c1e4055f3f2009977b9dcb9b7e643cd9256b6a

If this issue happens again, we require the specific functions.
